export const OrchidsData = [
  {
    id: 1,
    image:
      "https://cdn.orchideenwlodarczyk.de/images/xrlc_taichung_beauty_popup.jpg.pagespeed.ic.gq7mViCe10.jpg",
    name: "Taichung Beauty",
    origin: "Taiwan",
    color: "Pink",
    isSpecial: true,
    rating: 3,
    category: "Cattleya",
  },
  {
    id: 2,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/59/Phalaenopsis_amabilis_Orchi_198.jpg",
    name: "Phalaenopsis Amabilis",
    origin: "Southeast Asia",
    color: "White",
    isSpecial: false,
    rating: 4.5,
    category: "Phalaenopsis",
  },
  {
    id: 3,
    image:
      "https://clickorchid.com/cdn/shop/files/Untitleddesign_40_70fd0c07-dc85-4a11-a73d-958e1d2cdecb.png?v=1710151776",
    name: "Dendrobium Nobile",
    origin: "Himalayas",
    color: "White with purple tips",
    isSpecial: true,
    rating: 4.7,
    category: "Dendrobium",
  },
  {
    id: 4,
    image:
      "https://www.gardenia.net/wp-content/uploads/2023/03/lm5LsSSvKiOxvqttl2itCqxcNWGR4vyZKW5T6wZ6-1.webp",
    name: "Cymbidium Orchid",
    origin: "Asia and Australia",
    color: "Various (yellow, pink, red)",
    isSpecial: false,
    rating: 4.8,
    category: "Cymbidium",
  },
  {
    id: 5,
    image:
      "https://images.squarespace-cdn.com/content/v1/56953209df40f3e955611485/1612817042741-Q5PKJ971Q4LA5IZDHHSW/miltonia.JPG",
    name: "Miltonia Orchid",
    origin: "Brazil",
    color: "White with red markings",
    isSpecial: false,
    rating: 4.3,
    category: "Miltonia",
  },
  {
    id: 6,
    image:
      "https://images.immediate.co.uk/production/volatile/sites/10/2018/11/2048x1365-gg-Orchid-Cattleya-GettyImages-639671270-dcc1360.jpg?quality=90&resize=940,627",
    name: "Cattleya Orchid",
    origin: "Central and South America",
    color: "Purple, pink",
    isSpecial: true,
    rating: 4.9,
    category: "Cattleya",
  },
  {
    id: 7,
    image: "https://cdn.mos.cms.futurecdn.net/F6XAZrWmgZamJpjzeXG9hn.jpg",
    name: "Vanda Orchid",
    origin: "Asia",
    color: "Blue, purple",
    isSpecial: true,
    rating: 4.6,
    category: "Vanda",
  },
  {
    id: 8,
    image:
      "https://cdn.brilliantorchids.com/wp-content/uploads/2019/10/01-paphiopedilum-orchids-feature.jpg",
    name: "Paphiopedilum Orchid",
    origin: "Southeast Asia",
    color: "Green, brown",
    isSpecial: true,
    rating: 4.7,
    category: "Paphiopedilum",
  },
  {
    id: 9,
    image:
      "https://cdn.brilliantorchids.com/wp-content/uploads/2019/10/09-yellow-oncidium-feature.jpg",
    name: "Oncidium Orchid",
    origin: "South America",
    color: "Yellow, brown",
    isSpecial: false,
    rating: 4.4,
    category: "Oncidium",
  },
  {
    id: 10,
    image:
      "https://cdn.brilliantorchids.com/wp-content/uploads/2020/06/purple-zygopetalum-orchid-feature.jpg",
    name: "Zygopetalum Orchid",
    origin: "South America",
    color: "Purple, green",
    isSpecial: true,
    rating: 4.5,
    category: "Zygopetalum",
  },
  {
    id: 11,
    image:
      "https://cdn11.bigcommerce.com/s-ookf1bkiza/images/stencil/1280x1280/products/27158/39419/d7be112c-30cd-4f91-856f-d7ee921f0db2__53939.1703964360.jpg?c=2",
    name: "Stanhopea Orchid",
    origin: "Central and South America",
    color: "Yellow with burgundy spots",
    isSpecial: true,
    rating: 4.6,
    category: "Stanhopea",
  },
  {
    id: 12,
    image:
      "https://newworldorchids.com/wp-content/uploads/2016/11/specklinia-picta.jpg",
    name: "Pleurothallis Orchid",
    origin: "Central and South America",
    color: "Red, yellow",
    isSpecial: false,
    rating: 4.2,
    category: "Pleurothallis",
  },
  {
    id: 13,
    image:
      "https://images.squarespace-cdn.com/content/v1/544591e6e4b0135285aeb5b6/1514416238462-1YFVZKV807PNS596K8XH/Catasetum_osculatum_DSC_0443.jpg",
    name: "Catasetum Orchid",
    origin: "Central and South America",
    color: "Purple, green",
    isSpecial: true,
    rating: 4.4,
    category: "Catasetum",
  },
  {
    id: 14,
    image:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjNMSHtWxotIAVS0l14lIBxWyzFTuaxzqbvUtasqX4SpWRKFl_31KoCr1ukK8NwCNsEmrW-5Hll5Ilh7KQYiQ06CYTJTxc47TAJlREWu9I1QEkbdvjGe3Deb0UlvU1dwsg6TaG96Zt3eF4/s1600/1.jpeg",
    name: "Cycnoches Orchid",
    origin: "Central and South America",
    color: "White, green",
    isSpecial: true,
    rating: 4.5,
    category: "Cycnoches",
  },
  {
    id: 15,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Coelogyne_cristata_3.jpg/1200px-Coelogyne_cristata_3.jpg",
    name: "Coelogyne Orchid",
    origin: "Southeast Asia",
    color: "White, yellow",
    isSpecial: false,
    rating: 4.3,
    category: "Coelogyne",
  },
  {
    id: 16,
    image:
      "https://cdn.brilliantorchids.com/wp-content/uploads/2020/06/029-coconut-orchid-feature.jpg",
    name: "Maxillaria Orchid",
    origin: "Central and South America",
    color: "Red, yellow",
    isSpecial: true,
    rating: 4.4,
    category: "Maxillaria",
  },
];
